var apartments = [
    {id: 1, title: 'My cool apartment', description: 'My apartment description', cityId: 2, owner: 1, price: 50050, main_image: "./apartments_images/apartment_1.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_5.jpg", "./apartments_images/apartment_2.jpg","./apartments_images/apartment_8.jpg", "./apartments_images/apartment_7.jpg"], number_of_beds: 3, number_of_rooms: 1, address: '330 3rd Ave', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 2, title: 'My nice apartment', description: 'My nice apartment description', cityId: 6, owner: 2, price: 55000, number_of_beds: 1, number_of_rooms: 2, address: '330 3rd Ave', main_image:"./apartments_images/apartment_2.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_5.jpg", "./apartments_images/apartment_20.jpg","./apartments_images/apartment_8.jpg", "./apartments_images/apartment_7.jpg"], for_rent: false, for_sale: false},
    {id: 3, name: 'My cool apartment', title: 'My cool apartment', description: 'My apartment description', cityId: 17, owner: 1, price: 99000, main_image: "./apartments_images/apartment_3.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_15.jpg", "./apartments_images/apartment_21.jpg"], number_of_beds: 3, number_of_rooms: 1, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true,for_sale: false},
    {id: 4, name: 'My nice apartment', title: 'My nice apartment', description: 'My nice apartment description', cityId: 13, owner: 2, price: 150000, number_of_beds: 3, number_of_rooms: 1, address: 'Saloona 23 st', main_image: "./apartments_images/apartment_4.jpg", images: ["./apartments_images/apartment_14.jpg","./apartments_images/apartment_5.jpg", "./apartments_images/apartment_2.jpg"], for_rent: false, for_sale: true},
    {id: 5, title: 'My cool apartment', description: 'My apartment description', cityId: 4, owner: 1, price: 170000, main_image: "./apartments_images/apartment_5.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_12.jpg", "./apartments_images/apartment_8.jpg"], number_of_beds: 3, number_of_rooms: 2, address: 'Rozeni 423 st', sqft: 7500, status: 2, for_rent: false,for_sale: false},
    {id: 6, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 2, price: 200000, number_of_beds: 5, number_of_rooms: 3, address: 'Zurik 52 st', main_image: "./apartments_images/apartment_6.png", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_7.jpg", "./apartments_images/apartment_8.jpg"], for_rent: true, for_sale: true},
    {id: 7, title: 'My cool apartment', description: 'My apartment description', cityId: 15, owner: 1, price: 110000, main_image: "./apartments_images/apartment_7.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_5.jpg", "./apartments_images/apartment_2.jpg"], number_of_beds: 3, number_of_rooms: 5, address: 'Korab 41 st', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 8, title: 'My nice apartment', description: 'My nice apartment description', cityId: 21, owner: 2, price: 66000, number_of_beds: 4, number_of_rooms: 2, address: 'Moris 422 st 33s', main_image: "./apartments_images/apartment_9.jpg", images: ["./apartments_images/apartment_1.jpg","./apartments_images/apartment_12.jpg", "./apartments_images/apartment_13.jpg"], for_rent: false, for_sale: false},
    {id: 9, title: 'My cool apartment', description: 'My apartment description', cityId: 16, owner: 1, price: 200230, main_image: "./apartments_images/apartment_9.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: false, for_sale: false},
    {id: 10, title: 'My nice apartment', description: 'My nice apartment description', cityId: 12, owner: 2, price: 300521, number_of_beds: 1, number_of_rooms: 5, address: 'Alenby 3 st', main_image: "./apartments_images/apartment_10.jpg", images: ["./apartments_images/apartment_3.jpg","./apartments_images/apartment_4.jpg", "./apartments_images/apartment_21.jpg"], for_rent: true, for_sale: true},
    {id: 11, title: 'My cool apartment', description: 'My apartment description', cityId: 20, owner: 1, price: 330230, main_image: "./apartments_images/apartment_11.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: true},
    {id: 12, title: 'My nice apartment', description: 'My nice apartment description', cityId: 7, owner: 2, price: 400230, number_of_beds: 4, number_of_rooms: 1, address: 'Alenby 3 st', main_image: "./apartments_images/apartment_12.jpg", images: ["./apartments_images/apartment_1.jpg","./apartments_images/apartment_14.jpg", "./apartments_images/apartment_13.jpg"], for_rent: false, for_sale: false},
    {id: 13, title: 'My cool apartment', description: 'My apartment description', cityId: 8, owner: 1, price: 465100, main_image: "./apartments_images/apartment_13.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 14, title: 'My nice apartment', description: 'My nice apartment description', cityId: 9, owner: 2, price: 80000, number_of_beds: 2, number_of_rooms: 5, address: 'Alenby 3 st', main_image: "./apartments_images/apartment_14.jpg", images: ["./apartments_images/apartment_9.jpg","./apartments_images/apartment_7.jpg", "./apartments_images/apartment_21.jpg"], for_rent: true, for_sale: false},
    {id: 15, title: 'My cool apartment', description: 'My apartment description', cityId: 9, owner: 1, price: 300202, main_image: "./apartments_images/apartment_15.jpg", images: ["./apartments_images/apartment_19.jpg","./apartments_images/apartment_18.jpg", "./apartments_images/apartment_11.jpg"], number_of_beds: 3, number_of_rooms: 3, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 16, title: 'My nice apartment', description: 'My nice apartment description', cityId: 10, owner: 2, price: 400210, number_of_beds: 1, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "./apartments_images/apartment_16.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_5.jpg", "./apartments_images/apartment_2.jpg"], for_rent: true, for_sale: false},
    {id: 17, title: 'My cool apartment', description: 'My apartment description', cityId: 19, owner: 1, price: 195400, main_image: "./apartments_images/apartment_17.jpg", images: ["./apartments_images/apartment_14.jpg","./apartments_images/apartment_16.jpg", "./apartments_images/apartment_17.jpg"], number_of_beds: 3, number_of_rooms: 2, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 18, title: 'My nice apartment', description: 'My nice apartment description', cityId: 5, owner: 2, price: 400321, number_of_beds: 2, number_of_rooms: 3, address: 'Alenby 3 st', main_image: "./apartments_images/apartment_2.jpg", images: ["./apartments_images/apartment_18.jpg","./apartments_images/apartment_16.jpg", "./apartments_images/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 19, title: 'My cool apartment', description: 'My apartment description', cityId: 6, owner: 1, price: 103215, main_image: "./apartments_images/apartment_19.jpg", images: ["./apartments_images/apartment_4.jpg","./apartments_images/apartment_5.jpg", "./apartments_images/apartment_2.jpg"], number_of_beds: 3, number_of_rooms: 1, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 20, title: 'My nice apartment', description: 'My nice apartment description', cityId: 1, owner: 2, price: 70321, number_of_beds: 5, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "./apartments_images/apartment_20.jpg", images: ["./apartments_images/apartment_7.jpg","./apartments_images/apartment_1.jpg", "./apartments_images/apartment_2.jpg"], for_rent: true, for_sale: false
    }];


export {apartments};